---
title: "Multivariate normal distribution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multivariate normal distribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
To demonstrate the R package `algebraic.dist`, we consider the relatively
simple case of an observed sample of, we assume, i.i.d. random variables
$X_1,\ldots,X_n$ with multivariate normal distribution.

```{r setup}
library(algebraic.dist)
```

# Generating a sample

We define the parameters of the MVN with:
```{r}
M <- mvn(mu = c(0,1,2),
         sigma = matrix(c(1,0.5,0.5,
                          0.5,1,0.5,
                          0.5,0.5,1),
                        nrow = 3))
```

We observe a sample of size 100 with:
```{r}
n <- 100
data <- sampler(M)(n)
head(data, n = 8)
```


```{r}
support <- sup(M)
infinum(support)
supremum(support)
dim(support)
```


```{r}
X1 <- marginal(M, 1)
F1 <- cdf(X1)
curve(F1(x), from = -5, to = 5)
```

```{r}
X1X2 <- marginal(M, c(1,2))
rv <- sampler(X1X2)

# sample some data; could just use data directly
data.X1X2 <- rv(1000)

# scatter plot a 2d sample
plot(data.X1X2[,1], data.X1X2[,2], pch = 20, col = "blue")
```

